### ISSUE TITLE
Error when Archiving app using XCode

### ISSUE THREAD

**Issue by IjzerenHein** [rmrs/react-native-firebaseui#11]
Hi, first of all, thanks for this great package. In my opinion, this is the best way to show images from firebase-storage. 👍 
Everything runs fine, except when I try to archive the app in order to upload it to the app-store. It gives approx 18 errors, as can be seen in the screenshot.

Version: 0.0.1-alpha8
XCode: 10.1 (10B61)
react-native-firebase: 5.2.1

Do you have any idea what could be wrong?

![image](https://user-images.githubusercontent.com/6184593/53800584-5d287c00-3f3d-11e9-893d-62bdd5993dc0.png)

**Comment by erezrokah** [comment]
Hey @IjzerenHein and thank you :)
I'm not sure this is related to the library:
https://stackoverflow.com/questions/41709912/error-could-not-build-objective-c-module-firebase
https://stackoverflow.com/questions/47764165/could-not-build-objective-c-module-firebase?rq=1

Also if you just build (without archiving) does it work?
Running it on device/simulator works?

I know you said everything runs fine, I'm just not sure what "everything" means ;)

**Comment by IjzerenHein** [comment]
Hi @erezrokah ! So, building debug & release and running it on simulator and on real device works like a charm. At this stage only the archiving seems to fail.

**Comment by erezrokah** [comment]
That's strange indeed...
Have you managed to run our example successfully? 
Maybe you can generate a small example that reproduces the issue?

**Comment by IjzerenHein** [comment]
Here is a more detailed log:
![image](https://user-images.githubusercontent.com/6184593/53802220-94992780-3f41-11e9-839e-4c982e6c5987.png)

**Comment by IjzerenHein** [comment]
> That's strange indeed...
> Have you managed to run our example successfully?
> Maybe you can generate a small example that reproduces the issue?

I'll try to reproduce it with your example app 👍

**Comment by IjzerenHein** [comment]
@erezrokah Just for the record, the `SDWebImage` pod is missing from the example app, or was this intentional?

**Comment by erezrokah** [comment]
Don't think it is intentional. Good work on figuring it out and sorry

**Comment by IjzerenHein** [comment]
No worries, I'll continue figuring out whats wrong after lunch

**Comment by IjzerenHein** [comment]
Unfortunately (or luckily depending how you look at it), archiving the Example app produces the same problem when archiving:

![image](https://user-images.githubusercontent.com/6184593/53804479-e8a70a80-3f47-11e9-8251-019436f9339a.png)

**Comment by erezrokah** [comment]
Ok let me setup a dev environment with a new Xcode (haven't done it in a while) and I'll look into it

**Comment by IjzerenHein** [comment]
Awesome, thanks @erezrokah

**Comment by IjzerenHein** [comment]
Fixed by #13
