### ISSUE TITLE
Could you explain the use of this tool. 

### ISSUE THREAD

**Issue by mohbasheer** [rmrs/react-native-firebaseui#25]
Hi,

Thanks for the contribution.

Could you explain the use of this tool. Is it helping to log the message in firebase or something else?

**Comment by erezrokah** [comment]
The purpose of this library is to provide react native bindings over these libraries:
https://github.com/firebase/FirebaseUI-Android
https://github.com/firebase/FirebaseUI-iOS

More specifically it allows you, for example, to use an Image component in react native that is backed by a Firebase storage reference, thus enabling caching on Android and iOS (meaning the image won't be re-loaded every-time you open the app).

I'm not sure what you mean by your question, but this library doesn't do anything related to logging at the moment.

**Comment by mohbasheer** [comment]
Hi,

Thanks for the quick response. I understand the usage of this library now.

What I meant was. Currently we are using firebase to log user events.

For example.

When user submit the form and When user click the cancel button and When
user click on the help icon etc..
