### ISSUE TITLE
Can't compile for Android; `package ... does not exist`

### ISSUE THREAD

**Issue by jacobobryant** [rmrs/react-native-firebaseui#29]
Running `react-native run-android` gives me a bunch of `package ... does not exist` errors; e.g. these are the first two:

```
> Task :react-native-firebaseui:compileDebugJavaWithJavac FAILED
Note: [1] Wrote GeneratedAppGlideModule with: []
/home/arch/dev/lagukan/rn/lagukan/node_modules/react-native-firebaseui/android/src/main/java/io/rumors/reactnativefirebaseui/storage/FirebasePhotoViewManager.java:15: error: package com.facebook.yoga does not exist
import com.facebook.yoga.YogaConstants;
                        ^
/home/arch/dev/lagukan/rn/lagukan/node_modules/react-native-firebaseui/android/src/main/java/io/rumors/reactnativefirebaseui/storage/ExtendedPhotoView.java:15: error: package com.facebook.react.views.imagehelper does not exist
import com.facebook.react.views.imagehelper.ResourceDrawableIdHelper;
                                           ^
```

Any ideas on how to fix this? Maybe it's something similar to https://github.com/capitalone/react-native-pathjs-charts/issues/55? I'm a bit of a newb wrt react native, but I'll try messing around with it some more on Monday.

**Comment by erezrokah** [comment]
Hey @jacobobryant and thank you for opening this issue.
I’m currently on vacation and we’ll be able to look at this in about 10 days.
I’ll look into it when I come back.

**Comment by jacobobryant** [comment]
Looks like I've figured it out-- I had the following in my build.gradle:
```
maven {
    url "$rootDir/../node_modules/react-native/android"
    url "https://jitpack.io"
}
```
Not realizing it was supposed to be like this:
```
maven { url "$rootDir/../node_modules/react-native/android" }
maven { url "https://jitpack.io" }
```
There are other compilation issues, but those are just androidx migration errors.

**Comment by jacobobryant** [comment]
(For posterity, I fixed the androidx errors by bumping the glide dependency to 4.10.0. Jetifier wasn't handling it because Glide generates code.)
