### ISSUE TITLE
getting 'SDWebImage/SDWebImage.h' file not found Error on iOS

### ISSUE THREAD

**Issue by proserve** [rmrs/react-native-firebaseui#36]
I'm trying to install the library on iOS and I'm getting the following issue:

<img width="1183" alt="Screen Shot 2020-03-14 at 7 53 12 PM" src="https://user-images.githubusercontent.com/5354875/76685495-a66dda00-662d-11ea-92f9-f89eb4ed9b1a.png">

**Comment by erezrokah** [comment]
Hi @proserve, does the example in this repo work for you?

**Comment by proserve** [comment]
@erezrokah yes I did, and on iOS, I'm getting this issue:

<img width="1182" alt="Screen Shot 2020-03-15 at 2 30 23 PM" src="https://user-images.githubusercontent.com/5354875/76699720-ab806700-66c9-11ea-8eaa-d8ce4103d9b1.png">

**Comment by erezrokah** [comment]
Sorry for the late reply, I was able to get the example working after updating its dependencies:
https://github.com/rmrs/react-native-firebaseui/pull/37

Can you try again with the example, and align your Pod file with the same versions?

**Comment by proserve** [comment]
Thanks a lot, that PR fixes the issue.
