### ISSUE TITLE
import package to MainApplication.java

### ISSUE THREAD

**Issue by Manoj002** [rmrs/react-native-firebaseui#7]
Hello, while going through docs and implementing the package, 
i noticed while linking [this link](https://github.com/rmrs/react-native-firebaseui#android), the packages should be imported to MainApplicaition.java and RNFirebaseUiPackage() package should be added to the same.

**Comment by erezrokah** [comment]
Hey @Manoj002, thank you for opening this issue.
I'm not sure I understand the problem.
Can you provide step by step instructions on how to reproduce the problem you're having?
Also please specify React Native version, iOS/Android, OS, etc.
I think we only tested this library with React Native `~42.3`

**Comment by Manoj002** [comment]
Hello @erezrokah , thanks for your reply mate
im using:
"react-native": "0.56.0",
"react": "16.4.1"
"react-native-firebase": "^4.3.8",
"react-native-firebaseui": "0.0.1-alpha7"
Android[linux]
The main part is that i did the same as mentioned in docs but it didnt worked but when i imported that package in MainApplication.java it worked.

**Comment by erezrokah** [comment]
@Manoj002 so you saying the `react-native link react-native-firebase-ui` command didn't work?
We haven't really tested it with newer versions of React Native since the default is to have expo included and you need to eject anyway.

**Comment by Manoj002** [comment]
@erezrokah , im not saying that `react-native link react-native-firebase-ui` doesnt works, it did infact but as mentioned in docs it says to import `io.rumors.reactnativefirebaseui.RNFirebaseUiPackage` to MainActivity.java (here my app didnt work) but it should be imported in MainApplication.java(here my app worked perfectly)

**Comment by erezrokah** [comment]
@Manoj002 sorry for the late reply.
#8 should fix this issue
